ALTER TABLE announcements
  MODIFY COLUMN type ENUM(
    'GENERAL_NOTICE',
    'SCHEDULE_CHANGE',
    'HOLIDAY_REMINDER',
    'EMERGENCY_ADVISORY',
    'SYSTEM_MAINTENANCE',
    'COMMUNITY_EVENT'
  ) NOT NULL;
