import { Post } from "./types";

export const initialPosts: Post[] = [
  {
    id: "p1",
    title: "Zero Waste in Action: Reduce & Refuse",
    body: "Think before you buy. Pause and ask: Do I really need this? Say NO to single-use plastics, excessive packaging, unnecessary items. Every small decision contributes to a larger movement toward sustainability. Start with your daily habits and watch the ripple effect unfold in your community.",
    source: "MENRO-Candelaria, Quezon - National Zero Waste Month Tip of the Week",
    category: "Waste Tip", status: "Published", featured: true, author: "Admin",
    publishedDate: "Mar 21, 2026", lastEdited: "Mar 21, 2026", views: 142, commentCount: 2,
    tags: ["zero-waste", "tips"], images: [], scheduledDate: null, commentsEnabled: true,
    comments: [
      { id: "c1", author: "Maria Santos", text: "Very helpful tips! I started refusing plastic bags last week.", date: "Mar 22, 2026", likes: 3 },
      { id: "c2", author: "Juan Dela Cruz", text: "We should share this to more barangays!", date: "Mar 23, 2026", likes: 1 },
    ],
  },
  {
    id: "p2",
    title: "Community Clean-Up Drive 2026",
    body: "Join us for a community-wide clean-up drive this weekend. Together we can make Candelaria cleaner and greener. Bring your gloves, bags, and enthusiasm. Refreshments will be provided for all volunteers.",
    source: "MENRO-Candelaria, Quezon - Quarterly Barangay Clean-Up",
    category: "Event", status: "Published", featured: true, author: "Admin",
    publishedDate: "Mar 25, 2026", lastEdited: "Mar 24, 2026", views: 89, commentCount: 1,
    tags: ["event", "cleanup"], images: [], scheduledDate: null, commentsEnabled: true,
    comments: [
      { id: "c3", author: "Ana Reyes", text: "Count me in! I'll bring my family.", date: "Mar 25, 2026", likes: 2 },
    ],
  },
  {
    id: "p3",
    title: "Composting at Home: A Beginner's Guide",
    body: "Learn the basics of turning your kitchen scraps into nutrient-rich compost for your garden. This guide covers everything from choosing the right bin to maintaining proper moisture and temperature levels for optimal decomposition.",
    source: "",
    category: "Waste Tip", status: "Published", featured: false, author: "Admin",
    publishedDate: "Mar 18, 2026", lastEdited: "Mar 18, 2026", views: 67, commentCount: 0,
    tags: ["composting"], images: [], scheduledDate: null, commentsEnabled: true, comments: [],
  },
  {
    id: "p4",
    title: "Waste Segregation Reminder for All Residents",
    body: "A friendly reminder to all residents: please segregate your waste properly. Biodegradable, recyclable, and residual waste must be placed in separate bins for collection.",
    source: "MENRO-Candelaria, Quezon",
    category: "Waste Tip", status: "Draft", featured: false, author: "Admin",
    publishedDate: null, lastEdited: "Mar 15, 2026", views: 0, commentCount: 0,
    tags: ["reminder"], images: [], scheduledDate: null, commentsEnabled: true, comments: [],
  },
  {
    id: "p5",
    title: "Eco-Brick Workshop This Saturday",
    body: "Join us for a hands-on workshop where you'll learn how to create eco-bricks from plastic waste. Materials will be provided. Perfect for families and students looking for weekend activities.",
    source: "",
    category: "Event", status: "Scheduled", featured: false, author: "Admin",
    publishedDate: null, lastEdited: "Mar 10, 2026", views: 0, commentCount: 0,
    tags: ["workshop", "eco-brick"], images: [], scheduledDate: "2026-04-05T09:00", commentsEnabled: true, comments: [],
  },
  {
    id: "p6",
    title: "How to Reduce Food Waste at Home",
    body: "Simple tips and tricks to minimize food waste in your household and save money in the process. From meal planning to proper storage techniques, discover practical ways to reduce waste.",
    source: "",
    category: "Waste Tip", status: "Unpublished", featured: false, author: "Admin",
    publishedDate: "Mar 8, 2026", lastEdited: "Mar 12, 2026", views: 34, commentCount: 0,
    tags: ["food-waste"], images: [], scheduledDate: null, commentsEnabled: true, comments: [],
  },
  {
    id: "p7",
    title: "Tree Planting Activity in Barangay Park",
    body: "Be part of the greening initiative! Help us plant native trees in the barangay park. Every tree planted contributes to cleaner air and a more beautiful community for generations.",
    source: "MENRO-Candelaria, Quezon - Greening Program",
    category: "Event", status: "Published", featured: false, author: "Admin",
    publishedDate: "Mar 5, 2026", lastEdited: "Mar 5, 2026", views: 112, commentCount: 0,
    tags: ["tree-planting"], images: [], scheduledDate: null, commentsEnabled: true, comments: [],
  },
  {
    id: "p8",
    title: "DIY Natural Cleaning Solutions",
    body: "Ditch the chemicals! Learn how to make effective cleaning solutions from everyday household items like vinegar, baking soda, and lemon.",
    source: "",
    category: "Waste Tip", status: "Archived", featured: false, author: "Admin",
    publishedDate: "Feb 20, 2026", lastEdited: "Mar 2, 2026", views: 45, commentCount: 0,
    tags: ["diy", "cleaning"], images: [], scheduledDate: null, commentsEnabled: false, comments: [],
  },
];
