import type { CollectorNotification } from "./types";

export const mockCollectorNotifications: CollectorNotification[] = [
  {
    id: "cn-1",
    type: "admin-message",
    title: "Route Change — Skip Brgy. Mabolo",
    message: "Supervisor instruction: Skip Brgy. Mabolo Zone 2 today due to road closure on Rizal Street. Proceed directly to Brgy. San Roque.",
    time: "5 minutes ago",
    read: false,
    details: "Supervisor Mario Reyes has issued a route change for today's collection. Skip Brgy. Mabolo Zone 2 entirely due to a road closure on Rizal Street caused by utility maintenance. Proceed directly to Brgy. San Roque after completing Brgy. Poblacion. The skipped zone will be covered tomorrow.",
  },
  {
    id: "cn-2",
    type: "route-alert",
    title: "Route Assigned for Today",
    message: "Route B-7 (Brgy. Poblacion → Brgy. San Roque → Brgy. Guadalupe) has been assigned to you for today's shift.",
    time: "28 minutes ago",
    read: false,
    details: "You have been assigned Route B-7 for today, March 31, 2026. The route covers Brgy. Poblacion, Brgy. San Roque, and Brgy. Guadalupe with 14 pickup points. Shift starts at 6:00 AM. Truck #4 is assigned to this route.",
  },
  {
    id: "cn-3",
    type: "admin-message",
    title: "Priority Pickup — Municipal Hall",
    message: "Admin request: Prioritize pickup at the Municipal Hall compound before 8:00 AM. Event waste from last night's program.",
    time: "1 hour ago",
    read: false,
    details: "A priority pickup has been requested at the Municipal Hall compound. There is event waste from last night's barangay program that needs to be cleared before 8:00 AM when offices open. Please make this your first stop if possible.",
  },
  {
    id: "cn-4",
    type: "skip-acknowledged",
    title: "Skip Acknowledged — Stop #6",
    message: "Your skip at Stop #6 (Purok 3, Brgy. Poblacion) has been received and recorded by the admin.",
    time: "2 hours ago",
    read: false,
    details: "The admin has acknowledged your skip submission for Stop #6 at Purok 3, Brgy. Poblacion. Reason recorded: No waste placed outside / Resident not home. This stop has been marked as skipped in today's route log.",
  },
  {
    id: "cn-5",
    type: "route-completed",
    title: "Route Session Closed",
    message: "Your shift for Route B-7 has been successfully closed. 12 of 14 stops completed, 2 skipped.",
    time: "Yesterday, 11:45 AM",
    read: true,
    details: "Route B-7 session completed on March 30, 2026 at 11:45 AM. Summary: 12 stops completed, 2 stops skipped. Total collection time: 4 hours 32 minutes. All data has been synced to the admin dashboard.",
  },
  {
    id: "cn-6",
    type: "system-alert",
    title: "New Login Detected",
    message: "A new login to your account was detected from a Samsung Galaxy A15 device at 5:48 AM.",
    time: "Yesterday, 5:48 AM",
    read: true,
    details: "A new login session was initiated on your GreenWay Collector account. Device: Samsung Galaxy A15. Location: Candelaria, Quezon. Time: March 30, 2026 at 5:48 AM. If this was not you, please contact your supervisor immediately.",
  },
  {
    id: "cn-7",
    type: "route-alert",
    title: "Route Updated — Stop Order Changed",
    message: "Admin has re-ordered Route B-7 stops. Brgy. Guadalupe is now Stop #2 instead of Stop #8.",
    time: "Yesterday, 5:30 AM",
    read: true,
    details: "Route B-7 has been updated by the admin. The stop order has changed: Brgy. Guadalupe has been moved from position #8 to position #2 to accommodate a morning priority request. Please review the updated route before starting your shift.",
  },
  {
    id: "cn-8",
    type: "admin-message",
    title: "Reminder — Weigh All Bins Today",
    message: "Operations reminder: Please weigh all bins at each stop today. Data needed for the monthly waste audit report.",
    time: "2 days ago",
    read: true,
    details: "This is a reminder from the Operations team. Today is a weigh-day for the monthly waste audit. Please use the truck scale to weigh each bin before loading and log the weight using the app. This data is required for the MENRO monthly compliance report.",
  },
  {
    id: "cn-9",
    type: "skip-acknowledged",
    title: "Skip Acknowledged — Stop #11",
    message: "Your skip at Stop #11 (Brgy. San Roque Market) has been received and recorded.",
    time: "2 days ago",
    read: true,
    details: "The admin has acknowledged your skip at Stop #11, Brgy. San Roque Market. Reason recorded: Access blocked by parked vehicles. The admin has noted this for follow-up with barangay officials.",
  },
  {
    id: "cn-10",
    type: "route-completed",
    title: "Route Session Closed",
    message: "Your shift for Route A-3 has been successfully closed. All 10 stops completed.",
    time: "3 days ago",
    read: true,
    details: "Route A-3 session completed on March 28, 2026 at 10:30 AM. Summary: 10 of 10 stops completed, 0 skipped. Total collection time: 3 hours 45 minutes. Excellent completion rate.",
  },
  {
    id: "cn-11",
    type: "system-alert",
    title: "Password Changed Successfully",
    message: "Your account password was changed successfully on March 27, 2026 at 7:15 PM.",
    time: "4 days ago",
    read: true,
    details: "Your GreenWay Collector account password was changed on March 27, 2026 at 7:15 PM. If you did not make this change, please contact your supervisor or the MENRO IT team immediately.",
  },
  {
    id: "cn-12",
    type: "system-alert",
    title: "Two-Factor Authentication Enabled",
    message: "2FA has been enabled on your account by your administrator for enhanced security.",
    time: "5 days ago",
    read: true,
    details: "Two-Factor Authentication (2FA) has been enabled on your GreenWay Collector account. You will now be required to enter a verification code sent to your registered phone number when logging in from a new device.",
  },
  {
    id: "cn-13",
    type: "admin-message",
    title: "Holiday Schedule — Holy Week",
    message: "No collection on April 17–18 (Maundy Thursday & Good Friday). Resume normal schedule April 19.",
    time: "6 days ago",
    read: true,
    details: "MENRO Candelaria Operations Notice: There will be no garbage collection on April 17 (Maundy Thursday) and April 18 (Good Friday), 2026. Normal collection resumes on Saturday, April 19. Please plan your schedule accordingly.",
  },
  {
    id: "cn-14",
    type: "route-alert",
    title: "New Route Assigned — Route C-1",
    message: "You have been permanently reassigned from Route A-3 to Route C-1 starting next week.",
    time: "1 week ago",
    read: true,
    details: "Effective April 7, 2026, you have been reassigned from Route A-3 to Route C-1 covering Brgy. Mabolo and Brgy. Tagpos. This is a permanent reassignment. Please familiarize yourself with the new route before your first shift.",
  },
];
