import "./dashboard.css";

/** Shared spacing and hierarchy for the resident dashboard and its loading state. */
export const dashboardStyles = {
  page: "resident-dashboard mx-auto min-w-0 w-full max-w-[1440px] space-y-4 sm:space-y-5",
  greeting: "resident-dashboard-greeting min-w-0 justify-between gap-3",
  greetingActions: "resident-dashboard-greeting-actions shrink-0 items-center gap-2.5",
  dateBadge: "inline-flex h-10 max-w-full shrink-0 items-center gap-2 rounded-lg border border-border/60 bg-card/60 px-3 text-xs font-medium text-foreground tabular-nums whitespace-nowrap",
  overview: "resident-dashboard-overview items-stretch gap-4",
  collectionColumn: "min-w-0 h-full",
  truckColumn: "min-w-0 h-full",
  reportColumn: "resident-dashboard-report min-w-0 h-full",
  updates: "resident-dashboard-updates items-stretch gap-4",
  supporting: "resident-dashboard-supporting items-stretch gap-4",
  calendarColumn: "resident-dashboard-calendar-column min-w-0",
  calendarSection: "resident-dashboard-calendar-section min-w-0",
  calendarGrid: "resident-dashboard-calendar-grid border-border/70 p-4 shadow-none sm:p-5",
  calendarDays: "resident-dashboard-calendar-days grid grid-cols-7 gap-1",
  supportColumn: "resident-dashboard-support min-w-0 items-stretch gap-4",
  card: "min-w-0 rounded-2xl border border-border/70 bg-card",
  hero: "group flex min-w-0 flex-col justify-between gap-4 rounded-2xl border border-border/70 bg-card p-4 transition-colors duration-200 hover:border-primary/40 sm:p-5 motion-reduce:transition-none",
  label: "text-xs font-medium text-muted-foreground",
  icon: "flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary",
  heroTitle: "gw-heading line-clamp-2 break-words text-base leading-snug text-foreground",
  heroDescription: "mt-1 line-clamp-2 break-words text-xs leading-relaxed text-muted-foreground",
  heroFooter: "flex min-h-10 flex-wrap items-center justify-between gap-x-3 gap-y-1 border-t border-border/50 pt-3 text-xs",
  updateInner: "flex flex-1 flex-col gap-3 p-4 sm:p-5",
  updateHeader: "flex min-h-6 flex-wrap items-center justify-between gap-2",
  postBody: "resident-dashboard-post-body min-h-24 min-w-0 flex-1 items-start gap-4",
  postImage: "resident-dashboard-post-image shrink-0 rounded-xl border border-border/60",
  updateBody: "flex min-h-24 min-w-0 flex-1 flex-col gap-2",
  updateTitle: "gw-heading min-h-10 line-clamp-2 break-words text-base leading-snug text-foreground transition-colors group-hover:text-primary",
  updateExcerpt: "line-clamp-2 break-words text-sm leading-relaxed text-muted-foreground",
  updateFooter: "mt-auto flex min-h-10 shrink-0 items-center justify-end border-t border-border/50 pt-3",
} as const;
