import { AuditLogEntry } from "./types";

export const adminNames = [
  "Juan Dela Cruz",
  "Maria Santos",
  "Roberto Reyes",
  "Ana Garcia",
  "Pedro Mendoza",
];

export const moduleList = [
  "Accounts",
  "Posts",
  "Announcements",
  "Waste Reports",
  "Route Manager",
  "Resident Manager",
  "Driver Manager",
  "Landing Page",
  "Collection Schedule",
  "Barangay Manager",
  "Analytics",
] as const;

export const actionTypes = [
  "Login",
  "Logout",
  "Failed Login",
  "Created",
  "Edited",
  "Published",
  "Unpublished",
  "Archived",
  "Deleted",
  "Status Changed",
  "Role Changed",
  "Deactivated",
  "Reactivated",
  "Password Reset",
  "Exported",
  "Sent",
  "Scheduled",
  "Flagged",
  "Note Added",
  "Visibility Toggled",
];

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "LOG-001",
    timestamp: "2026-03-31T14:23:45",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Status Changed",
    module: "Waste Reports",
    affectedRecord: "RPT-2026-00142",
    summary: "Changed status from Under Review to Resolved",
    severity: "change",
    beforeValue: "Under Review",
    afterValue: "Resolved",
    ipAddress: "192.168.1.105",
    metadata: { "Response Added": "Issue resolved after site inspection" },
  },
  {
    id: "LOG-002",
    timestamp: "2026-03-31T14:18:12",
    adminName: "Maria Santos",
    adminRole: "Content Admin",
    actionType: "Published",
    module: "Posts",
    affectedRecord: "Post #47",
    summary: "Published post: Community Clean-up Drive Schedule",
    severity: "routine",
    ipAddress: "192.168.1.112",
  },
  {
    id: "LOG-003",
    timestamp: "2026-03-31T13:55:30",
    adminName: "Roberto Reyes",
    adminRole: "Operations Admin",
    actionType: "Deleted",
    module: "Announcements",
    affectedRecord: "ANN-2026-089",
    summary: "Deleted outdated announcement: Holiday Schedule Change",
    severity: "critical",
    ipAddress: "192.168.1.108",
  },
  {
    id: "LOG-004",
    timestamp: "2026-03-31T13:42:08",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Role Changed",
    module: "Accounts",
    affectedRecord: "Admin: Ana Garcia",
    summary: "Changed role from Content Admin to Operations Admin",
    severity: "change",
    beforeValue: "Content Admin",
    afterValue: "Operations Admin",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-005",
    timestamp: "2026-03-31T13:15:00",
    adminName: "Ana Garcia",
    adminRole: "Operations Admin",
    actionType: "Created",
    module: "Route Manager",
    affectedRecord: "Route #12",
    summary: "Created new route: Brgy. Malabanban Norte – Morning",
    severity: "routine",
    ipAddress: "192.168.1.115",
  },
  {
    id: "LOG-006",
    timestamp: "2026-03-31T12:48:33",
    adminName: "Pedro Mendoza",
    adminRole: "Reports Admin",
    actionType: "Flagged",
    module: "Waste Reports",
    affectedRecord: "RPT-2026-00139",
    summary: "Flagged report as duplicate of RPT-2026-00135",
    severity: "change",
    ipAddress: "192.168.1.120",
  },
  {
    id: "LOG-007",
    timestamp: "2026-03-31T12:30:00",
    adminName: "Maria Santos",
    adminRole: "Content Admin",
    actionType: "Edited",
    module: "Landing Page",
    affectedRecord: "Hero Section",
    summary: "Updated hero banner image and tagline text",
    severity: "change",
    beforeValue: "Your Partner in Clean Communities",
    afterValue: "Building Greener Communities Together",
    ipAddress: "192.168.1.112",
  },
  {
    id: "LOG-008",
    timestamp: "2026-03-31T11:55:18",
    adminName: "Roberto Reyes",
    adminRole: "Operations Admin",
    actionType: "Failed Login",
    module: "Accounts",
    affectedRecord: "Admin: Roberto Reyes",
    summary: "Failed login attempt — incorrect password",
    severity: "critical",
    ipAddress: "203.177.45.88",
  },
  {
    id: "LOG-009",
    timestamp: "2026-03-31T11:45:00",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Deactivated",
    module: "Resident Manager",
    affectedRecord: "Resident: Carlo Dimayuga",
    summary: "Deactivated resident account due to duplicate registration",
    severity: "critical",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-010",
    timestamp: "2026-03-31T11:20:45",
    adminName: "Ana Garcia",
    adminRole: "Operations Admin",
    actionType: "Exported",
    module: "Analytics",
    affectedRecord: "Monthly Report – March 2026",
    summary: "Exported analytics dashboard as PDF",
    severity: "routine",
    ipAddress: "192.168.1.115",
  },
  {
    id: "LOG-011",
    timestamp: "2026-03-31T10:58:12",
    adminName: "Pedro Mendoza",
    adminRole: "Reports Admin",
    actionType: "Note Added",
    module: "Waste Reports",
    affectedRecord: "RPT-2026-00141",
    summary: "Added internal note: Awaiting verification from barangay captain",
    severity: "routine",
    ipAddress: "192.168.1.120",
  },
  {
    id: "LOG-012",
    timestamp: "2026-03-31T10:30:00",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Created",
    module: "Accounts",
    affectedRecord: "Admin: Sofia Navarro",
    summary: "Created new admin account with Content Admin role",
    severity: "change",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-013",
    timestamp: "2026-03-31T10:12:30",
    adminName: "Maria Santos",
    adminRole: "Content Admin",
    actionType: "Sent",
    module: "Announcements",
    affectedRecord: "ANN-2026-092",
    summary: "Sent announcement: Truck Delay Notice for Brgy. Poblacion",
    severity: "routine",
    ipAddress: "192.168.1.112",
  },
  {
    id: "LOG-014",
    timestamp: "2026-03-31T09:45:00",
    adminName: "Roberto Reyes",
    adminRole: "Operations Admin",
    actionType: "Login",
    module: "Accounts",
    affectedRecord: "Admin: Roberto Reyes",
    summary: "Logged in successfully",
    severity: "routine",
    ipAddress: "192.168.1.108",
  },
  {
    id: "LOG-015",
    timestamp: "2026-03-31T09:30:22",
    adminName: "Ana Garcia",
    adminRole: "Operations Admin",
    actionType: "Visibility Toggled",
    module: "Landing Page",
    affectedRecord: "Partners Section",
    summary: "Toggled section visibility from visible to hidden",
    severity: "change",
    beforeValue: "Visible",
    afterValue: "Hidden",
    ipAddress: "192.168.1.115",
  },
  {
    id: "LOG-016",
    timestamp: "2026-03-31T09:10:00",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Password Reset",
    module: "Driver Manager",
    affectedRecord: "Driver: Ramon Villanueva",
    summary: "Reset driver account password",
    severity: "change",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-017",
    timestamp: "2026-03-31T08:55:40",
    adminName: "Pedro Mendoza",
    adminRole: "Reports Admin",
    actionType: "Status Changed",
    module: "Waste Reports",
    affectedRecord: "RPT-2026-00140",
    summary: "Changed status from Submitted to Under Review",
    severity: "change",
    beforeValue: "Submitted",
    afterValue: "Under Review",
    ipAddress: "192.168.1.120",
  },
  {
    id: "LOG-018",
    timestamp: "2026-03-31T08:30:00",
    adminName: "Maria Santos",
    adminRole: "Content Admin",
    actionType: "Archived",
    module: "Posts",
    affectedRecord: "Post #39",
    summary: "Archived post: January Waste Reduction Tips",
    severity: "change",
    ipAddress: "192.168.1.112",
  },
  {
    id: "LOG-019",
    timestamp: "2026-03-30T17:45:00",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Deleted",
    module: "Accounts",
    affectedRecord: "Admin: Removed Test Account",
    summary: "Permanently deleted test admin account",
    severity: "critical",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-020",
    timestamp: "2026-03-30T16:20:15",
    adminName: "Roberto Reyes",
    adminRole: "Operations Admin",
    actionType: "Edited",
    module: "Barangay Manager",
    affectedRecord: "Brgy. San Juan",
    summary: "Changed zone classification from Residential to Mixed-Use",
    severity: "change",
    beforeValue: "Residential",
    afterValue: "Mixed-Use",
    ipAddress: "192.168.1.108",
    metadata: { "Priority Flag": "Enabled" },
  },
  {
    id: "LOG-021",
    timestamp: "2026-03-30T15:10:00",
    adminName: "Ana Garcia",
    adminRole: "Operations Admin",
    actionType: "Reactivated",
    module: "Resident Manager",
    affectedRecord: "Resident: Elena Torres",
    summary: "Reactivated previously deactivated resident account",
    severity: "change",
    ipAddress: "192.168.1.115",
  },
  {
    id: "LOG-022",
    timestamp: "2026-03-30T14:00:00",
    adminName: "Pedro Mendoza",
    adminRole: "Reports Admin",
    actionType: "Exported",
    module: "Waste Reports",
    affectedRecord: "Filtered Export",
    summary: "Exported 47 filtered waste reports as CSV",
    severity: "routine",
    ipAddress: "192.168.1.120",
  },
  {
    id: "LOG-023",
    timestamp: "2026-03-30T13:30:00",
    adminName: "Maria Santos",
    adminRole: "Content Admin",
    actionType: "Scheduled",
    module: "Announcements",
    affectedRecord: "ANN-2026-091",
    summary: "Scheduled announcement for April 1, 2026 at 8:00 AM",
    severity: "routine",
    ipAddress: "192.168.1.112",
  },
  {
    id: "LOG-024",
    timestamp: "2026-03-30T12:15:00",
    adminName: "Juan Dela Cruz",
    adminRole: "Super Admin",
    actionType: "Edited",
    module: "Collection Schedule",
    affectedRecord: "Reminder Settings",
    summary: "Changed resident reminder timing from 1 hour to 30 minutes before",
    severity: "change",
    beforeValue: "1 hour before",
    afterValue: "30 minutes before",
    ipAddress: "192.168.1.105",
  },
  {
    id: "LOG-025",
    timestamp: "2026-03-30T11:00:00",
    adminName: "Roberto Reyes",
    adminRole: "Operations Admin",
    actionType: "Deactivated",
    module: "Route Manager",
    affectedRecord: "Route #8",
    summary: "Deactivated route: Brgy. Bukal Sur – Afternoon",
    severity: "critical",
    ipAddress: "192.168.1.108",
  },
];
