import type { ResidentNotification } from "./types";

export const mockNotifications: ResidentNotification[] = [
  {
    id: "1",
    type: "collection-reminder",
    title: "Collection Reminder",
    message: "Your biodegradable garbage collection is tomorrow.",
    time: "2 minutes ago",
    read: false,
    details: "Your garbage collection is tomorrow at 8:00 AM. Please place your biodegradable waste in the designated green bin by 7:30 AM.",
  },
  {
    id: "2",
    type: "truck-near",
    title: "Truck Is Near Your Area",
    message: "The collection truck is approaching Barangay Malabanban Norte.",
    time: "15 minutes ago",
    read: false,
    details: "The collection truck is now close to your barangay. Please prepare your garbage and place it outside for pickup.",
  },
  {
    id: "3",
    type: "schedule-change",
    title: "Schedule Change Notice",
    message: "Tomorrow's biodegradable collection has been moved to Thursday.",
    time: "1 hour ago",
    read: false,
    details: "Due to inclement weather, the biodegradable collection originally scheduled for Wednesday, March 31, has been moved to Thursday, April 1. Reason: Tropical storm warning in the area.",
  },
  {
    id: "4",
    type: "report-update",
    title: "Report #1042 Resolved",
    message: "Your report about illegal dumping has been resolved by MENRO.",
    time: "3 hours ago",
    read: false,
  },
  {
    id: "5",
    type: "new-content",
    title: "New Content Posted",
    message: "Check out the latest waste segregation guide for your barangay.",
    time: "5 hours ago",
    read: false,
  },
  {
    id: "6",
    type: "collection-done",
    title: "Collection Complete",
    message: "Garbage collection in your area has been completed for today.",
    time: "Yesterday",
    read: true,
    details: "Collection in Barangay Malabanban Norte was completed at 10:45 AM on March 29, 2026. All scheduled waste types were collected.",
  },
  {
    id: "7",
    type: "missed-collection",
    title: "Missed Collection Alert",
    message: "No collection was recorded in your area today.",
    time: "Yesterday",
    read: true,
    details: "Our records show that no garbage collection was completed in your area today. If your garbage was not picked up, you may submit a missed collection report.",
  },
  {
    id: "8",
    type: "system-announcement",
    title: "MENRO Announcement",
    message: "New recycling drop-off point at the municipal hall every Saturday.",
    time: "2 days ago",
    read: true,
    details: "Starting April 5, 2026, MENRO Candelaria will operate a recycling drop-off point at the Municipal Hall every Saturday from 7:00 AM to 12:00 PM. Accepted materials include plastic bottles, aluminum cans, and cardboard. This initiative is part of our expanded waste diversion program.",
  },
  {
    id: "9",
    type: "collection-reminder",
    title: "Collection Reminder",
    message: "Residual waste collection is scheduled for tomorrow.",
    time: "3 days ago",
    read: true,
    details: "Your residual waste collection is tomorrow at 9:00 AM. Please use the black bin for non-recyclable, non-biodegradable waste.",
  },
  {
    id: "10",
    type: "report-update",
    title: "Report #1038 Under Review",
    message: "Your clogged drainage report is now being reviewed by the team.",
    time: "March 25, 2026",
    read: true,
  },
];
