import "./communityContent.css";

/** Shared geometry for the resident community feed and its loading placeholders. */
export const communityContentStyles = {
  page: "community-content mx-auto min-w-0 w-full max-w-[1400px] pb-4 lg:pb-6",
  detailPage: "community-content mx-auto min-w-0 w-full max-w-[1000px] pb-4 lg:pb-6",
  detailArticle: "community-post-article grid min-w-0",
  detailHeader: "community-post-header grid min-w-0 gap-3 text-left",
  detailTitle: "community-post-title min-w-0 break-words font-bold tracking-tight text-foreground [overflow-wrap:anywhere]",
  detailBody: "community-post-body min-w-0 text-foreground/85",
  detailImage: "community-post-image relative flex w-full items-center justify-center overflow-hidden rounded-xl border border-border/80 bg-muted/20",
  detailThumbnails: "flex min-w-0 items-center gap-2 overflow-x-auto px-1 py-1 scrollbar-thin",
  detailThumbnail: "community-post-thumbnail relative shrink-0 overflow-hidden rounded-lg border-2 transition-colors duration-200 cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
  header: "mb-4 min-w-0 space-y-1 sm:mb-5",
  headerTitle: "gw-page-title sm:text-ui-page-lg text-foreground tracking-tight",
  headerDescription: "text-xs sm:text-sm text-muted-foreground mt-0.5",
  stack: "space-y-4 sm:space-y-5",
  filterRow: "community-content-filter-row min-w-0 items-center gap-2",
  sort: "community-content-sort min-w-0 shrink-0",
  featuredCard: "community-content-featured group/featured relative min-w-0 overflow-hidden rounded-2xl border border-border/80 bg-card",
  featuredGrid: "community-content-featured-grid items-stretch",
  featuredDetails: "community-content-featured-details flex min-w-0 flex-col justify-center gap-5",
  featuredMedia: "community-content-featured-media relative min-w-0",
  featuredTitle: "community-content-featured-title gw-heading break-words leading-tight tracking-tight text-foreground",
  readButton: "community-content-read-button h-11 gap-2 px-4 text-xs",
  featuredImage: "absolute inset-0 flex h-full w-full items-center justify-center overflow-hidden bg-muted/30",
  featuredFooter: "mt-auto flex min-w-0 flex-wrap items-center justify-between gap-3 pt-2",
  featuredArrow: "community-content-featured-arrow absolute z-20 h-11 w-11 -translate-y-1/2 rounded-full bg-card/95 shadow-sm opacity-0 pointer-events-none transition-opacity duration-200 group-hover/featured:opacity-100 group-hover/featured:pointer-events-auto group-focus-within/featured:opacity-100 group-focus-within/featured:pointer-events-auto [@media(hover:none)]:opacity-100 [@media(hover:none)]:pointer-events-auto motion-reduce:transition-none",
  featuredPagination: "absolute bottom-2 left-1/2 z-20 flex max-w-[calc(100%-2rem)] -translate-x-1/2 items-center overflow-x-auto scrollbar-none",
  carouselDotButton: "flex h-5 shrink-0 cursor-pointer items-center justify-center rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring",
  sectionHeading: "flex flex-wrap items-center justify-between gap-x-3 gap-y-1",
  grid: "community-content-grid min-w-0 items-stretch gap-4",
  cardImage: "relative flex aspect-[16/9] items-center justify-center overflow-hidden border-b border-border/50 bg-muted/30",
  cardContent: "flex min-w-0 flex-1 flex-col justify-between gap-4 p-4 sm:p-5",
  cardFooter: "mt-auto flex min-w-0 flex-wrap items-center justify-between gap-3 border-t border-border/50 pt-3.5",
  cardMetadata: "flex min-w-0 flex-1 flex-col items-start gap-1.5 text-xs text-muted-foreground",
  reactionSize: "community-content-reaction shrink-0",
} as const;
