import "./reportDetail.css";

export const reportDetailStyles = {
  page: "resident-report-detail mx-auto min-w-0 w-full max-w-3xl space-y-0 pb-4 md:space-y-4 md:pb-6 lg:space-y-5 lg:pb-8",
  card: "resident-report-detail-card min-w-0 divide-y divide-border/60 md:overflow-hidden md:rounded-2xl md:border md:border-border/80 md:bg-card md:shadow-2xs",
  headerSection: "resident-report-detail-section space-y-2.5 py-4 md:space-y-3 md:p-5 lg:p-6",
  section: "resident-report-detail-section min-w-0 space-y-3.5 py-4 md:space-y-4 md:p-5 lg:p-6",
  header: "resident-report-detail-header flex min-w-0 items-center justify-between gap-3",
  referenceGroup: "resident-report-detail-reference-group min-w-0 space-y-1",
  referenceRow: "flex min-w-0 items-center gap-2",
  reference: "resident-report-detail-reference gw-heading min-w-0 break-words text-lg tabular-nums tracking-tight text-foreground lg:text-2xl [overflow-wrap:anywhere]",
  copy: "gw-action-ghost inline-flex size-8 shrink-0 items-center justify-center rounded-lg border transition-colors cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
  submitted: "resident-report-detail-submitted flex min-w-0 flex-wrap items-center gap-3 pt-0.5 text-ui-caption text-muted-foreground lg:gap-4 lg:text-xs",
  summary: "resident-report-detail-summary grid min-w-0 grid-cols-1 gap-3 md:grid-cols-2 md:gap-4",
  summaryCard: "resident-report-detail-summary-card flex min-w-0 items-start gap-3 rounded-xl border border-border/70 bg-muted/30 p-3 dark:bg-muted/20 lg:gap-3.5 lg:p-4",
  summaryIcon: "resident-report-detail-summary-icon flex size-10 shrink-0 items-center justify-center rounded-xl border shadow-2xs [&_svg]:size-5",
  description: "resident-report-detail-description max-h-56 overflow-y-auto rounded-xl border border-border/70 bg-muted/30 p-3 text-xs leading-relaxed text-foreground/90 dark:bg-muted/20 md:p-4 md:text-sm [overflow-wrap:anywhere]",
  photosSection: "resident-report-detail-section min-w-0 space-y-2.5 py-4 md:p-5 lg:p-6",
  photos: "resident-report-detail-photos flex min-w-0 items-start gap-3 overflow-x-auto pb-1",
  photo: "resident-report-detail-photo relative size-12 shrink-0 overflow-hidden rounded-xl border border-border/80 bg-muted/20 md:size-16 lg:size-20",
  progressSection: "resident-report-detail-section min-w-0 space-y-4 py-4 md:space-y-4 md:p-5 lg:space-y-5 lg:p-6",
  progressLabels: "resident-report-detail-progress-labels grid min-w-0 grid-cols-4 text-center",
  milestone: "resident-report-detail-milestone min-w-0 pb-3.5",
  responseSection: "resident-report-detail-section min-w-0 space-y-2 border-t border-border/60 bg-muted/20 py-4 md:p-5 lg:p-6",
  response: "break-words text-sm text-foreground/90 leading-relaxed bg-card p-3.5 rounded-xl border border-border/70 shadow-2xs [overflow-wrap:anywhere]",
  actions: "resident-report-detail-actions space-y-3 pt-3 lg:pt-2",
  action: "resident-report-detail-action flex w-full min-w-0 items-center justify-between gap-3 rounded-2xl border border-border/80 bg-card p-4 shadow-2xs",
  actionIcon: "resident-report-detail-action-icon flex size-10 shrink-0 items-center justify-center rounded-xl border border-border/70 bg-muted/70 text-muted-foreground",
  actionTitle: "resident-report-detail-action-title block break-words text-sm font-bold text-foreground",
  actionDescription: "resident-report-detail-action-description block break-words text-xs font-normal leading-relaxed text-muted-foreground",
} as const;
